B-Team-Final-Exercise/force-app/main/default/objects/Contact/fields/LastEditorDateType__c.field-meta.xml
<CustomField>
    <fullName>LastEditorDateType__c</fullName>
    <label>LastEditorDateType</label>
    <type>DateTime</type>
</CustomField>

B-Team-Final-Exercise/force-app/main/default/objects/Contact/fields/LastEditorType__c.field-meta.xml
<CustomField>
    <fullName>LastEditorType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LastEditorType</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

B-Team-Final-Exercise/force-app/main/default/classes/ContactServiceLayer.cls
public with sharing class ContactServiceLayer {
    public static void updateFields (Map<Id,Contact> oldRecords, List<Contact> newRecords) {
        for (Contact cont: newRecords) {
            //Here we use the contact id, to get the older version of the record.
            Contact oldContact = oldRecords.get(cont.Id);    
            //once we get the older version, we can get any field's value from older version to compare.
            if(cont.AccountId != oldContact.AccountId) {
                cont.LastEditorType__c = cont.LastModifiedById;
                cont.LastEditorDateType__c = DateTime.now();
                System.debug('LastEditorTypes is updated');
            }
        }
    }
}